# Generated by Django 5.1 on 2024-08-24 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='created',
            field=models.DateField(blank=True, null=True),
        ),
    ]
